modmap:
  - name: Global Config
    window:
      not:
        - /^steam_app_*$/
        - /^steam_app_default$/
        - Need for Speed™ Most Wanted
    application:
      not:
        - /^steam_app_*$/
        - /^steam_app_default$/
        - Need for Speed™ Most Wanted
        
    remap:
      CapsLock:
        alone: Esc
        alone_timeout_millis: 200
        held: Ctrl_L
      Esc: CapsLock
