"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

format = """[╭](fg:white) [](#ffffff)[$os ](fg:#3a9efd bg:white)[ ](#ffffff)$username$directory$all$line_break$character"""

right_format = """$cmd_duration${custom.jj}$time"""

palette = "lilac"

# "mPrimary": "#b58fff",
# "mOnPrimary": "#000000",
# "mSecondary": "#c79aff",
# "mOnSecondary": "#000000",
# "mTertiary": "#d8b4ff",
# "mOnTertiary": "#000000",
# "mError": "#ff6f9b",
# "mOnError": "#000000",
# "mSurface": "#000000",
# "mOnSurface": "#e8d8ff",
# "mSurfaceVariant": "#110d1a",
# "mOnSurfaceVariant": "#b58fff",
# "mOutline": "#4c3a70",
# "mShadow": "#000000",
# "mHover": "#d8b4ff",
# "mOnHover": "#000000",

[palettes.lilac]
white     = "#ffffff"
primary   = "#b58fff"
secondary = "#c79aff"
tertiary  = "#d8b4ff"
surface   = "#e8d8ff"
error     = "#ff6f9b"
outline   = "#4c3a70"

[os]
format = "$symbol"
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = '󰣇'
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[character]
success_symbol = "[╰─❯](#ffffff)"
error_symbol = "[╰─×](#ff0000)"

[cmd_duration]
min_time = 500
format = '(fg:current_line)[](fg:primary bg:orange)[ $duration ](fg:foreground bg:box)'

[direnv]
disabled = false
symbol = " "

[nix_shell]
heuristic = true

[git_branch]
disabled = true
format = "[ $symbol $branch ]($style) "
symbol = ""
style = "#00ff00"

[git_commit]
tag_disabled = false
style = "#00ffa6"

[git_status]
disabled = true
staged = "+${count}"
untracked = "?${count}"
modified = "!${count}"

[directory]
# format = "[](#3a9efd)[$path]($style)[ ](#3a9efd)"
format = "[](outline)[$path]($style)[ ](outline)"
style = "fg:tertiary bg:outline"
truncate_to_repo=false

[username]
# style_user = "#3a9efd"
style_user = "primary"
show_always = true

[time]
# format = "[$time](#ffff00)"
format = "[$time](tertiary)"
time_format = "%I:%M %p"
disabled = false

[[battery.display]]
threshold = 20
style = 'bold red'

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship", "--truncate-name=6"]
format = "$output "
